spring:
  datasource:
    username: root
    password: password
    url: jdbc:h2:mem:to_do_list_db
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true